name: Publish to Prod

on:
    # Triggers the workflow on push events for the main branch
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.GH_PACKAGES_USER }}
                  password: ${{ secrets.GH_PACKAGES_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t ghcr.io/nymeria-sys/ny-health-check-prod:latest -f Dockerfile .
                  docker tag ghcr.io/nymeria-sys/ny-health-check-prod:latest ghcr.io/nymeria-sys/ny-health-check-prod:${{ github.sha }}
                  docker push ghcr.io/nymeria-sys/ny-health-check-prod:latest
                  docker push ghcr.io/nymeria-sys/ny-health-check-prod:${{ github.sha }}